/**
 * Training plan data model.
 *
 * In the skateboard phase, this is generated by the AI companion
 * and parsed from the chat response (same pattern as runner context).
 * In the bicycle phase, this gets persisted to Supabase.
 */

export interface Workout {
  day: string; // e.g. "Mon", "Tue"
  type: "easy" | "long" | "tempo" | "interval" | "rest" | "cross" | "race";
  distance: string | null; // e.g. "4", "6-8" — in miles
  description: string; // e.g. "Easy pace, conversational effort"
  completed: boolean;
}

export interface PlanWeek {
  weekNumber: number; // 1, 2, etc.
  label: string; // e.g. "Week 1 — Assessment"
  totalMiles: string; // e.g. "18-22"
  workouts: Workout[];
}

export interface TrainingPlan {
  phase: string; // e.g. "2-Week Assessment", "Base Building Phase 1"
  summary: string; // Brief explanation of the plan's purpose
  weeks: PlanWeek[];
  generatedAt: string; // ISO timestamp
}

export const EMPTY_PLAN: TrainingPlan | null = null;

/**
 * Parse a training plan from a companion message.
 * Looks for <plan>...</plan> JSON block at the end of the message.
 */
export function parsePlanFromMessage(
  rawMessage: string
): { cleanMessage: string; plan: TrainingPlan | null } {
  const planMatch = rawMessage.match(/<plan>([\s\S]*?)<\/plan>/);

  if (!planMatch) {
    return { cleanMessage: rawMessage, plan: null };
  }

  const cleanMessage = rawMessage.replace(/<plan>[\s\S]*?<\/plan>/, "").trim();

  try {
    const parsed = JSON.parse(planMatch[1]);
    const plan: TrainingPlan = {
      phase: parsed.phase || "Training Plan",
      summary: parsed.summary || "",
      weeks: (parsed.weeks || []).map((w: Record<string, unknown>, i: number) => ({
        weekNumber: w.weekNumber || i + 1,
        label: w.label || `Week ${i + 1}`,
        totalMiles: w.totalMiles || "—",
        workouts: ((w.workouts as Array<Record<string, unknown>>) || []).map((wo: Record<string, unknown>) => ({
          day: wo.day || "",
          type: wo.type || "easy",
          distance: wo.distance || null,
          description: wo.description || "",
          completed: false,
        })),
      })),
      generatedAt: new Date().toISOString(),
    };
    return { cleanMessage, plan };
  } catch {
    return { cleanMessage: rawMessage, plan: null };
  }
}
