/**
 * Training plan data model.
 *
 * In the skateboard phase, this is generated by the AI companion
 * and parsed from the chat response (same pattern as runner context).
 * In the bicycle phase, this gets persisted to Supabase.
 */

export interface Workout {
  day: string; // e.g. "Mon", "Tue"
  type: "easy" | "long" | "tempo" | "interval" | "rest" | "cross" | "race";
  distance: string | null; // e.g. "4", "6-8" — in miles
  description: string; // e.g. "Easy pace, conversational effort"
  completed: boolean;
}

export interface PlanWeek {
  weekNumber: number; // 1, 2, etc.
  label: string; // e.g. "Week 1 — Assessment"
  totalMiles: string; // e.g. "18-22"
  phaseIndex: number; // Which phase this week belongs to
  isRestWeek: boolean;
  workouts: Workout[];
}

export interface PlanPhase {
  index: number;
  name: string; // e.g. "Phase 0 — Pre-Phase"
  shortName: string; // e.g. "Pre-Phase"
  description: string; // 1-2 line description
  startWeek: number;
  endWeek: number;
}

export interface TrainingPlan {
  phase: string; // e.g. "2-Week Assessment", "Base Building Phase 1"
  summary: string; // Brief explanation of the plan's purpose
  phases: PlanPhase[];
  weeks: PlanWeek[];
  generatedAt: string; // ISO timestamp
}

export const EMPTY_PLAN: TrainingPlan | null = null;

/**
 * Convert a GeneratedPlan (from the plan engine) into the TrainingPlan format
 * that the frontend currently renders. This is a bridge until we upgrade
 * TrainingPlanView to render GeneratedPlan directly.
 */
export function convertGeneratedPlan(generated: {
  phases?: Array<{ name: string; shortName: string; description: string; startWeek: number; endWeek: number }>;
  weeks?: Array<{
    weekNumber: number;
    phaseName: string;
    phaseShortName: string;
    isRestWeek: boolean;
    totalMiles: number;
    workouts: Array<{
      day: string;
      miles: number | null;
      type: string;
      description: string;
    }>;
  }>;
  totalWeeks?: number;
  generatedAt?: string;
}): TrainingPlan {
  // Build phase metadata
  const phases: PlanPhase[] = (generated.phases ?? []).map((p, i) => ({
    index: i,
    name: `Phase ${i} — ${p.shortName}`,
    shortName: p.shortName,
    description: p.description,
    startWeek: p.startWeek,
    endWeek: p.endWeek,
  }));

  const phaseName = generated.phases?.[0]?.name ?? "Training Plan";
  const summary = generated.phases
    ?.map((p) => `${p.shortName} (${p.startWeek}-${p.endWeek})`)
    .join(" → ") ?? "";

  // Build a lookup: weekNumber → phaseIndex
  const weekToPhase: Record<number, number> = {};
  for (const p of phases) {
    for (let w = p.startWeek; w <= p.endWeek; w++) {
      weekToPhase[w] = p.index;
    }
  }

  return {
    phase: `${generated.totalWeeks ?? 0}-Week Plan`,
    summary: `${phaseName} through Race Week. ${summary}`,
    phases,
    weeks: (generated.weeks ?? []).map((w) => ({
      weekNumber: w.weekNumber,
      label: `Week ${w.weekNumber} — ${w.phaseShortName}${w.isRestWeek ? " (Rest)" : ""}`,
      totalMiles: String(w.totalMiles),
      phaseIndex: weekToPhase[w.weekNumber] ?? 0,
      isRestWeek: w.isRestWeek,
      workouts: w.workouts.map((wo) => ({
        day: wo.day,
        type: (wo.type === "threshold" || wo.type === "yasso" || wo.type === "fartlek"
          ? "tempo"
          : wo.type === "race-pace-long"
            ? "long"
            : wo.type) as Workout["type"],
        distance: wo.miles !== null ? String(wo.miles) : null,
        description: wo.description,
        completed: false,
      })),
    })),
    generatedAt: generated.generatedAt ?? new Date().toISOString(),
  };
}

/**
 * Parse a training plan from a companion message.
 * Looks for <plan>...</plan> JSON block at the end of the message.
 */
export function parsePlanFromMessage(
  rawMessage: string
): { cleanMessage: string; plan: TrainingPlan | null } {
  const planMatch = rawMessage.match(/<plan>([\s\S]*?)<\/plan>/);

  if (!planMatch) {
    return { cleanMessage: rawMessage, plan: null };
  }

  const cleanMessage = rawMessage.replace(/<plan>[\s\S]*?<\/plan>/, "").trim();

  try {
    const parsed = JSON.parse(planMatch[1]);
    const plan: TrainingPlan = {
      phase: parsed.phase || "Training Plan",
      summary: parsed.summary || "",
      phases: [],
      weeks: (parsed.weeks || []).map((w: Record<string, unknown>, i: number) => ({
        weekNumber: w.weekNumber || i + 1,
        label: w.label || `Week ${i + 1}`,
        totalMiles: w.totalMiles || "—",
        phaseIndex: 0,
        isRestWeek: false,
        workouts: ((w.workouts as Array<Record<string, unknown>>) || []).map((wo: Record<string, unknown>) => ({
          day: wo.day || "",
          type: wo.type || "easy",
          distance: wo.distance || null,
          description: wo.description || "",
          completed: false,
        })),
      })),
      generatedAt: new Date().toISOString(),
    };
    return { cleanMessage, plan };
  } catch {
    return { cleanMessage: rawMessage, plan: null };
  }
}
